// <auto-generated />
using System;
using FriendMap.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FriendMap.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416181457_AddSocialTableMessages")]
    partial class AddSocialTableMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FriendMap.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsGhostModeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ghost_mode_enabled");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<bool>("ShareIntentionsWithFriends")
                        .HasColumnType("boolean")
                        .HasColumnName("share_intentions_with_friends");

                    b.Property<bool>("SharePresenceWithFriends")
                        .HasColumnType("boolean")
                        .HasColumnName("share_presence_with_friends");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.FriendRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid")
                        .HasColumnName("addressee_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_friend_relations");

                    b.HasIndex("AddresseeId")
                        .HasDatabaseName("ix_friend_relations_addressee_id");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique()
                        .HasDatabaseName("ix_friend_relations_requester_id_addressee_id");

                    b.ToTable("friend_relations", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.ModerationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<Guid?>("ReportedSocialTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_social_table_id");

                    b.Property<Guid?>("ReportedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_user_id");

                    b.Property<Guid?>("ReportedVenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_venue_id");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_moderation_reports");

                    b.HasIndex("ReportedSocialTableId")
                        .HasDatabaseName("ix_moderation_reports_reported_social_table_id");

                    b.HasIndex("ReportedUserId")
                        .HasDatabaseName("ix_moderation_reports_reported_user_id");

                    b.HasIndex("ReportedVenueId")
                        .HasDatabaseName("ix_moderation_reports_reported_venue_id");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_moderation_reports_reporter_user_id");

                    b.ToTable("moderation_reports", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.NotificationDeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_token");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_device_tokens");

                    b.HasIndex("UserId", "Platform", "DeviceToken")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_device_tokens_user_id_platform_device_token");

                    b.ToTable("notification_device_tokens", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.NotificationOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_outbox");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_outbox_user_id");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_notification_outbox_status_next_attempt_at_utc");

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.SocialTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_user_id");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("join_policy");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_social_tables");

                    b.HasIndex("HostUserId")
                        .HasDatabaseName("ix_social_tables_host_user_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_social_tables_venue_id");

                    b.ToTable("social_tables", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.SocialTableMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("SocialTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("social_table_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_social_table_messages");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_social_table_messages_user_id");

                    b.HasIndex("SocialTableId", "CreatedAtUtc")
                        .HasDatabaseName("ix_social_table_messages_social_table_id_created_at_utc");

                    b.ToTable("social_table_messages", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.SocialTableParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("SocialTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("social_table_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_social_table_participants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_social_table_participants_user_id");

                    b.HasIndex("SocialTableId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_social_table_participants_social_table_id_user_id");

                    b.ToTable("social_table_participants", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.UserInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_interests");

                    b.HasIndex("UserId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_user_interests_user_id_tag");

                    b.ToTable("user_interests", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_provider_id");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_claimed");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility_status");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("ExternalProviderId")
                        .HasDatabaseName("ix_venues_external_provider_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_venues_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.VenueAffluenceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveUsersEstimated")
                        .HasColumnType("integer")
                        .HasColumnName("active_users_estimated");

                    b.Property<string>("AggregatedAgeJson")
                        .HasColumnType("text")
                        .HasColumnName("aggregated_age_json");

                    b.Property<string>("AggregatedGenderJson")
                        .HasColumnType("text")
                        .HasColumnName("aggregated_gender_json");

                    b.Property<DateTimeOffset>("BucketEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_end_utc");

                    b.Property<DateTimeOffset>("BucketStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_start_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DensityLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("density_level");

                    b.Property<bool>("IsSuppressedForPrivacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suppressed_for_privacy");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_venue_affluence_snapshots");

                    b.HasIndex("VenueId", "BucketStartUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_venue_affluence_snapshots_venue_id_bucket_start_utc");

                    b.ToTable("venue_affluence_snapshots", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.VenueCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<string>("VisibilityLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility_level");

                    b.HasKey("Id")
                        .HasName("pk_venue_checkins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_venue_checkins_user_id");

                    b.HasIndex("VenueId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_venue_checkins_venue_id_expires_at_utc");

                    b.ToTable("venue_checkins", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.VenueIntention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<string>("VisibilityLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility_level");

                    b.HasKey("Id")
                        .HasName("pk_venue_intentions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_venue_intentions_user_id");

                    b.HasIndex("VenueId", "StartsAtUtc", "EndsAtUtc")
                        .HasDatabaseName("ix_venue_intentions_venue_id_starts_at_utc_ends_at_utc");

                    b.ToTable("venue_intentions", (string)null);
                });

            modelBuilder.Entity("FriendMap.Api.Models.FriendRelation", b =>
                {
                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friend_relations_app_users_addressee_id");

                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friend_relations_app_users_requester_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.ModerationReport", b =>
                {
                    b.HasOne("FriendMap.Api.Models.SocialTable", null)
                        .WithMany()
                        .HasForeignKey("ReportedSocialTableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_moderation_reports_social_tables_reported_social_table_id");

                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_moderation_reports_app_users_reported_user_id");

                    b.HasOne("FriendMap.Api.Models.Venue", null)
                        .WithMany()
                        .HasForeignKey("ReportedVenueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_moderation_reports_venues_reported_venue_id");

                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_reports_app_users_reporter_user_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.NotificationDeviceToken", b =>
                {
                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_device_tokens_app_users_user_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.NotificationOutboxItem", b =>
                {
                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_outbox_app_users_user_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.SocialTable", b =>
                {
                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_tables_app_users_host_user_id");

                    b.HasOne("FriendMap.Api.Models.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_tables_venues_venue_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.SocialTableMessage", b =>
                {
                    b.HasOne("FriendMap.Api.Models.SocialTable", null)
                        .WithMany()
                        .HasForeignKey("SocialTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_table_messages_social_tables_social_table_id");

                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_table_messages_app_users_user_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.SocialTableParticipant", b =>
                {
                    b.HasOne("FriendMap.Api.Models.SocialTable", null)
                        .WithMany()
                        .HasForeignKey("SocialTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_table_participants_social_tables_social_table_id");

                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_table_participants_app_users_user_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.UserInterest", b =>
                {
                    b.HasOne("FriendMap.Api.Models.AppUser", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_interests_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FriendMap.Api.Models.VenueAffluenceSnapshot", b =>
                {
                    b.HasOne("FriendMap.Api.Models.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venue_affluence_snapshots_venues_venue_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.VenueCheckIn", b =>
                {
                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venue_checkins_app_users_user_id");

                    b.HasOne("FriendMap.Api.Models.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venue_checkins_venues_venue_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.VenueIntention", b =>
                {
                    b.HasOne("FriendMap.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venue_intentions_app_users_user_id");

                    b.HasOne("FriendMap.Api.Models.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venue_intentions_venues_venue_id");
                });

            modelBuilder.Entity("FriendMap.Api.Models.AppUser", b =>
                {
                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
